repo_url: https://github.com/kentaokamoto/DocTest
site_name: KentaOkamoto Doc
site_url: https://github.com/kentaokamoto/DocTest/
site_description: Documentation of KentaOkamoto
site_author: Kenta Okamoto

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

copyright: 'Copyright &copy; 2020- OUXT Polaris'


markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true
  - fontawesome_markdown
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: ⚓︎
      toc_depth: 3
nav:
  - Home: index.md
  - Tutorials:  
    - guid.md
